---
abstract: 'An interface to the Pushwoosh Remote API v1.3'
author:
  - 'Mike Cartmell, C<< <mike at mikec.me> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0.31
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Pushwoosh
no_index:
  directory:
    - inc
    - t
requires:
  Furl: 1
  JSON: 2.53
  Params::Validate: 1.07
  Try::Tiny: 0.12
  perl: 5.6.0
resources:
  bugtracker: http://github.com/mcartmell/WebService-Pushwoosh/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mcartmell/WebService-Pushwoosh
version: 0.02
